"""profiles and resources with specs

Revision ID: b2608f46ba1e
Revises: 
Create Date: 2023-02-05 13:34:38.440378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2608f46ba1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('social', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('info_source',
    sa.Column('r_id', sa.BigInteger(), nullable=False),
    sa.Column('r_type', sa.Enum('SOCIAL_CHAT', 'CHANNEL', 'WEBSITE', 'LITERATURE', name='resourcetype'), nullable=True),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='resourcelevel'), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('r_id')
    )
    op.create_table('spec',
    sa.Column('sid', sa.SmallInteger(), nullable=False),
    sa.Column('naming', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('res_spec',
    sa.Column('res_id', sa.SmallInteger(), nullable=False),
    sa.Column('spec_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['res_id'], ['spec.sid'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['info_source.r_id'], ),
    sa.PrimaryKeyConstraint('res_id', 'spec_id')
    )
    op.create_table('user_spec',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['spec.sid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'spec_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_spec')
    op.drop_table('res_spec')
    op.drop_table('spec')
    op.drop_table('info_source')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
